config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  resources :arts

  get 'home/index'

  root 'home#index'

  get 'arts/move_higher/:id' => 'arts#move_higher', :as => 'arts_move_higher'
  get 'arts/move_lower/:id' => 'arts#move_lower', :as => 'arts_move_lower'

  get 'arts/move_to_top/:id' => 'arts#move_to_top', :as => 'arts_move_to_top'
  get 'arts/move_to_bottom/:id' => 'arts#move_to_bottom', :as => 'arts_move_to_bottom'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login
  
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_taggable
  acts_as_list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:username, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all.order(position: :asc)
  end

  def move_to_top
    @art = Art.find(params[:id])
    if !@art.position.nil?
      @art.move_to_top
    end
    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :no_content }
    end
  end

  def move_to_bottom
    @art = Art.find(params[:id])
    if !@art.position.nil?
      @art.move_to_bottom
    end
    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :no_content }
    end
  end

  def move_lower
    @art = Art.find(params[:id])
    if !@art.position.nil?
      @art.move_lower
    end
    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :no_content }
    end
  end

  def move_higher
    @art = Art.find(params[:id])
    if !@art.position.nil?
      @art.move_higher
    end
    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :no_content }
    end
  end

  def hide
    @art = Art.find(params[:id])
    if !@art.position.nil?
      @art.remove_from_list
    end
    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :no_content }
    end
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    @art.tag_list = art_params[:tag_list]

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:name, :description, :image, :remove_image, :tag_list, :hidden)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    tag = params[:tag]
    all_arts = Art.where(hidden: false).order(position: :asc)
    if (!tag.blank?)
      @arts = all_arts.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 9)
    else
      @arts = all_arts.paginate(:page => params[:page], :per_page => 9)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/arts/_form.html.erb
<%= form_for @art, html: { multipart: true } do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, placeholder: "description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, value: @art.tag_list.join(', '), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br />
    <%= f.file_field :image, class: "form-control" %>
    <% if f.object.image? %>
      <br />
      <%= image_tag f.object.image.medium.url %>
      <br />
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :hidden %>
    <%= f.check_box :hidden %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-success btn-lg btn-block" %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h1>Editing Art</h1>

        <%= render 'form' %>

        <%= link_to 'Show', @art %> |
        <%= link_to 'Back', arts_path %>
      </div>
    </div>
  </div>
</div>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Arts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Position</th>
      <th>Name</th>
      <th>Description</th>
      <th>Tags</th>
      <th>Image</th>
      <th>Hidden</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td>
          <center>
            <%= link_to 'Δ', arts_move_to_top_path(:id => art.id) %><br />
            <%= link_to '▲', arts_move_higher_path(:id => art.id) %><br />
            <%= art.position %><br />
            <%= link_to '▼', arts_move_lower_path(:id => art.id) %><br />
            <%= link_to '∇', arts_move_to_bottom_path(:id => art.id) %>
          </center>
        </td>
        <td><%= art.name %></td>
        <td><%= art.description %></td>
        <td><%= art.tag_list %></td>
        <td>
          <% if art.image? %>
            <%= image_tag art.image.small.url %>
          <% end %>
        </td>
        <td><%= art.hidden %></td>
        <td><%= link_to 'Edit', edit_art_path(art) %></td>
        <td><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/arts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h1>New Art</h1>

        <%= render 'form' %>

        <%= link_to 'Back', arts_path %>
      </div>
    </div>
  </div>
</div>

app/views/arts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @art.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @art.description %>
        </p>

        <p>
          <strong>Tags:</strong>
          <%= @art.tag_list %>
        </p>

        <p>
          <strong>Image:</strong>
           <% if @art.image? %>
              <%= image_tag @art.image.small.url %><br />
           <% end %>
        </p>

        <%= link_to 'Edit', edit_art_path(@art) %> |
        <%= link_to 'Back', arts_path %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<center><h1><%= link_to "chuteki | gallery", root_path %></h1></center>
<center><a href="/">all</a> // <a href="/?tag=original">original</a> // <a href="/?tag=fanart">fanart</a></center>
<center><%= will_paginate @arts %></center>

<div id="gallery" class="container">
  <% i=0 %>
  <% total_works = @arts.count %>
  <% if total_works < 1 %>
    There are no works to display!
  <% end %>
  <% for work in @arts %>
    <% if i%3==0 %>
      <div class="row">
    <% end %>
    <div class="col-md-4">
      <div class="thumbnail center-block" style="width:275px;height:auto;overflow:hidden;border:transparent;">
        <a href="#" data-toggle="modal" data-target="#<%=i%>"><img src="<%= work.image.medium.url %>"></a>
        <center><%= work.name %></center>
      </div>
    </div>

    <div class="modal fade" id="<%=i%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel<%=i%>">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel<%=i%>"><%= work.name %></h4>
          </div>
          <div class="modal-body">
            <center><img src="<%=work.image.url%>" style="max-width:100%;height:auto;"></center>

            <br />
            <span id="next" class="form-control-static pull-right"><a class="btn btn-default btn-xs" onclick="goto(<%=i%>, <%=i + 1%>)">&#x3e;</a></span>
            <span id="prev" class="form-control-static pull-left"><a class="btn btn-default btn-xs" onclick="goto(<%=i%>, <%=i - 1%>)">&#x3c;</a></span>
            <center><%= work.description %></center>
          </div>
          <div class="modal-footer">

             <div style="float:left;color:#737373;">
               <% work.tag_list.each do |tag| %>
                <a class="btn btn-default btn-xs" data-dismiss="modal" onclick="javascript:window.location='/?tag=<%= tag %>'"><%= tag %></a>
                <% end %>
             </div>
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="hide(<%=i%>);">Close</button>
          </div>
        </div>
      </div>
    </div>

    <% i+=1 %>
    <% if i%3==0 || i == total_works %>
      </div>
    <% end %>
  <% end %>
</div>

<center><%= will_paginate @arts %></center>

<footer>
  <div id="footer">
    <center>
      <%= link_to root_path do %>
        <i class="fa fa-home"></i>
      <% end %> |
      <a href="http://gallery.chuteki.com/"><i class="fa fa-image"></i></a> |
      <a href="http://chuteki.tumblr.com/"><i class="fa fa-tumblr"></i></a> |
      <a href="http://twitter.com/_chuteki"><i class="fa fa-twitter"></i></a> |
      <a href="http://instagram.com/chuteki"><i class="fa fa-instagram"></i></a> |
      <a href="mailto:info@chuteki.com"><i class="fa fa-envelope-o"></i></a> |
      <%= link_to new_admin_session_path do %>
        <i class="fa fa-user"></i>
      <% end %>
    </center>
  </div>
</footer>

<span id="total_works" style="display:none"><%= @arts.count %></span>

<script>
var total_works = parseInt($("#total_works").html(), 10)

function hide(id) {
  $('#'+id).modal('hide');
}

function goto(current, next) {
  $('#'+current).modal('hide');

  if (next > total_works+1) {
    return
  } else if (next < -1) {
    return
  }

  $('#'+next).modal('show');

  current_modal = next
}

document.onkeydown = checkKey;

function checkKey(e) {
  e = e || window.event;

  var activeModal = -1;

  for (var i = 0; i < total_works; i++) {
    if ($('#'+ i).is(':visible')) {
      activeModal = i;
      break
    }
  }

  if (activeModal == -1) {
    return;
  }

  if (e.keyCode == '37') {
    goto(activeModal, activeModal-1);
  } else if (e.keyCode == '39') {
    goto(activeModal, activeModal+1);
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>chuteki | gallery</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<meta name="google-site-verification" content="uTn40mKmgXkPXtlSAHhzGK8qCev_Izc0jbUhu9WLwpM" />

<style type="text/css">
  a:link {text-decoration: none; background-color: none; color: #666;}      /* unvisited link */
  a:visited {text-decoration: none; background-color: none; color: #666;}   /* visited link */
  a:hover {text-decoration: none; background-color: white; color: #99E0FF;}     /* mouse over link */
  a:active {text-decoration: none; background-color: white; color: #99E0FF;}    /* selected link */
  * {
    font-family: 'Raleway', sans-serif;
  }
</style>

</head>
<body>

<% if admin_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to root_path do %>
          <span class="navbar-brand">Home</span>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Art Manager<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Art", arts_path, :class => "navbar-link" %></li>
              <li><%= link_to "Upload", new_art_path, :class => "navbar-link" %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit", edit_admin_registration_path, :class => "navbar-link" %></li>
              <li><%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => "navbar-link" %></li>
            </ul>
          </li>

          <li><%= link_to "Settings", arts_path %></li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>

<footer>
</footer>
</html>